#!/usr/bin/env bash

# case $HOSTNAME in
#   kuro)  export LAN=eno1   ;;
#   shiro) export LAN=wlp3s0 ;;
# esac


# Only have workspaces for primary monitor
bspc monitor -d {1,2,3,4,5}

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config -m primary bottom_padding 60

# Rules
bspc rule -r '*'

bspc rule -a Pinentry                  state=floating center=on
bspc rule -a Emacs                     split_ratio=0.28 state=tiled
bspc rule -a Firefox                   split_ratio=0.32
bspc rule -a feh                       state=fullscreen
bspc rule -a 'Emacs:org*'              state=floating
bspc rule -a 'Emacs:scratch'           state=floating
bspc rule -a 'Emacs:emacs-everywhere'  state=floating sticky=on
bspc rule -a '*:scratch'               state=floating sticky=on center=on border=off rectangle=1000x800+0+0
bspc rule -a "mpv"                     state=floating
bspc rule -a Spotify                   state=tiled desktop='^5' follow=on

#
for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done
