#!/usr/bin/env sh

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config border_width 1
bspc config window_gap 0

bspc config normal_border_color "#2E3440"
bspc config active_border_color "#2E3440"
bspc config focused_border_color "#D8DEE9"
bspc config presel_feedback_color "#D8DEE9"

# Extra padding for polybar
bspc config -m primary top_padding 0
bspc config -m primary bottom_padding 60
